### ISSUE TITLE
NetAlertX docker container filling up disk with empty directories and files

### ISSUE THREAD

**Issue by pschaer** [jokob-sk/NetAlertX#1046]
In a fresh installation of NetalertX which was basically left running unattended for a few months, the host Debian Bookworm suddenly started complaining about "no space left on device". 
Indeed, `df -h` showed 100% Inode usage for /dev/sda1, indicating a large amount of small files.
I traced this to "/var/lib/docker/overlay2/1f0926c3328ebcb63d947586ec95d84f5c4849e606fefa3c147551de972af001/diff/tmp" which contained millions(!!!) of empty directories in the form "cron.######" (where ###### is a random string) and thousands of empty files like "sess_*".
The offending folder was belonging to a netalertx container. A new empty folder would be created every 1-2 seconds.
Stopping the netalertx container resolved the issue.

Has this issue been reported previously? 
Maybe a misconfiguration can lead to such issues?

Any help is greatly appreciated.

Kind regards
Pascal

**Comment by jokob-sk** [comment]
Hi @pschaer ,

Thanks for the report.

It's first time hearing about this.

Could you please post your docker compose and check your app.log if you see anything suspicious?

I'm also travelling and have only access to my phone for the next 3 weeks so resolving the problem will take some time.

**Comment by pschaer** [comment]
Hi @jokob-sk 

Thanks for your fast reply. 
**The issue with the empty directories ("cron.######") created every 1-2 seconds has disappeared after updating to the latest version.**
Still, empty files are still created every 30 seconds in /tmp inside the container:
```
docker-03:/tmp# ls -latr --full-time
total 8
drwxr-xr-x    1 root     root          4096 2025-04-11 23:27:09 +0200 ..
-rw-------    1 nginx    www-data         0 2025-04-12 08:51:20 +0200 sess_h88rjorfds2bcum1nrscuv0jvg
-rw-------    1 nginx    www-data         0 2025-04-12 08:51:51 +0200 sess_nspmhchtpo1cpv7gs3kp9cdk5p
-rw-------    1 nginx    www-data         0 2025-04-12 08:52:21 +0200 sess_6tqf3muq450pl80qr12dfuvb20
-rw-------    1 nginx    www-data         0 2025-04-12 08:52:51 +0200 sess_l1qa0niavtu87mu191p01rtgm6
-rw-------    1 nginx    www-data         0 2025-04-12 08:53:21 +0200 sess_bfcehd49ksokg6hd47k6vrnhgd
-rw-------    1 nginx    www-data         0 2025-04-12 08:53:51 +0200 sess_qgovnekmpioshgvkaha0f34ual
-rw-------    1 nginx    www-data         0 2025-04-12 08:54:21 +0200 sess_tianj2g5ubua15pr85iqpc306h
-rw-------    1 nginx    www-data         0 2025-04-12 08:54:51 +0200 sess_cirgp5g02l73a5l0ma7gujl8li
-rw-------    1 nginx    www-data         0 2025-04-12 08:55:21 +0200 sess_77sc8gpr12p5107i2u24pg6r32
-rw-------    1 nginx    www-data         0 2025-04-12 08:55:51 +0200 sess_vqnpljpcqmf4db0vo3jhtb0h7b
-rw-------    1 nginx    www-data         0 2025-04-12 08:56:21 +0200 sess_cjqud2s6vgn9u0ng4jleibumku
-rw-------    1 nginx    www-data         0 2025-04-12 08:56:51 +0200 sess_u3992bb1op7vjlt28isrrrf6qr
-rw-------    1 nginx    www-data         0 2025-04-12 08:57:21 +0200 sess_929kr5oh8emibdnmpp1bb12c82
-rw-------    1 nginx    www-data         0 2025-04-12 08:57:52 +0200 sess_vuhfmr3sltkohsra21jtrcisjj
-rw-------    1 nginx    www-data         0 2025-04-12 08:58:22 +0200 sess_7qfd87tgfkbslu34e591ek1vjt

```
This leads to nginx.
The same happens on another instance of NetAlertX, where approx. 1320 "sess_*"-files have accumulated, from 11 hours back.
The container has been running for much longer, so they seem to be cleared up regularly. 

**I guess all is fine after all and I'm closing the issue.**

For completeness, here's my docker-compose:
```
services:
  netalertx:
    image: jokobsk/netalertx:latest
    container_name: netalertx
    network_mode: host
    privileged: true
    restart: always
    environment:
      - HOST_USER_ID=1047
      - HOST_USER_GID=100
      - PORT=20211
      - TZ=Europe/Zurich
    volumes:
      - /mnt/docker/netalertx/config:/app/config
      - /mnt/docker/netalertx/db:/app/db
      - /mnt/docker/netalertx/logs:/app/front/log   
```

Kind regards
Pascal
