### ISSUE TITLE
Mounting FontAwesome Pro no longer works

### ISSUE THREAD

**Issue by D3SOX** [jokob-sk/NetAlertX#594]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

After updating to 24.3.19 [this way from the docs](https://github.com/jokob-sk/Pi.Alert/blob/849c39d75db771463c4cc8b25886d0225fce6150/docs/ICONS.md#-pro-font-awesome-icons) to mount FontAwesome Pro results in missing icons when mounting version 6.4.2 in my case.
![image](https://github.com/jokob-sk/Pi.Alert/assets/24937357/9bd836f4-c84a-424c-a3c3-66d9464c61ca)

### Expected Behavior

Work like before

### Steps To Reproduce

Try to mount FontAwesome Pro

### pialert.conf

I don't think that's relevant

### docker-compose.yml

```yml
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${APP_DATA_LOCATION}/pialert/config:/home/pi/pialert/config
      - ${APP_DATA_LOCATION}/pialert/db/:/home/pi/pialert/db/
      # FontAwesome Pro
      - /home/nico/pialert/fontawesome-pro-6.4.2-web:/home/pi/pialert/front/lib/AdminLTE/bower_components/font-awesome:ro
    environment:
      - TZ=${TZ}
      - HOST_USER_ID=${HOST_USER_ID}
      - HOST_USER_GID=${HOST_USER_GID}
      - PORT=${PORT}
      - LOG_LEVEL=${LOG_LEVEL}
```

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @D3SOX ,

Thanks for the report. 

Can you try to test the dev image once this build finishes: https://github.com/jokob-sk/Pi.Alert/actions/runs/8342660269?

```yaml
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert_dev:latest"
    network_mode: "host"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${APP_DATA_LOCATION}/pialert/config:/home/pi/pialert/config
      - ${APP_DATA_LOCATION}/pialert/db/:/home/pi/pialert/db/
      # FontAwesome Pro
      - /home/nico/pialert/fontawesome-pro-6.4.2-web:/home/pi/pialert/front/lib/AdminLTE/bower_components/font-awesome:ro
    environment:
      - TZ=${TZ}
      - HOST_USER_ID=${HOST_USER_ID}
      - HOST_USER_GID=${HOST_USER_GID}
      - PORT=${PORT}
      - LOG_LEVEL=${LOG_LEVEL}
    ```
