### ISSUE TITLE
Dev branch in jokobsk/netalertx:latest

### ISSUE THREAD

**Issue by corasaniti** [jokob-sk/NetAlertX#620]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Hi 
I'm migrating to the new netalertx repository. I downloaded the following image

`jokobsk/netalertx:latest`

and I expected it to point to the latest stable version of pi.alert (24.3.19)
It's correct that I see the dev branch in the latest `jokobsk/netalertx:latest`?

### Expected Behavior

See stable version of pialert instead dev branch in `jokobsk/netalertx:latest`

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @corasaniti ,

Yes, that's currently the case. It will re-sync with the next stable release and the prod image of netaletx & pi.alert will be the same from there on onward for a while.

**Comment by jokob-sk** [comment]
released 🚀 -> closing

**Comment by corasaniti** [comment]
@jokob-sk 
Thank's for your job. An info: why can't I access my `config `and `db `folders? Who is the `_rpc user`? This is my docker-compose

```
version: "3"
services:
  netalertx:
    container_name: netalertx
    image: jokobsk/netalertx
    ports:
      - "20211:20211"
    dns:
      - 192.168.2.1
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /home/pi/docker/netalertx/config:/app/config
      - /home/pi/docker/netalertx/db/:/app/db
      - /home/pi/docker/netalertx/log/:/app/front/log
    environment:
      - TZ=Europe/Rome
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
```

Thank you

![Cattura](https://github.com/jokob-sk/NetAlertX/assets/5001932/246ebbd6-b331-4662-b316-b5db2546ffaa)
