### ISSUE TITLE
(name not found)

### ISSUE THREAD

**Issue by stanelie** [jokob-sk/NetAlertX#815]
Possibly a user error, but I am running both pi.alert and NetAlertX on the same network to evaluate both, and I find I like the features of NetAlertX better, but the name recognition of pi.alert is better.

For example, a Windows device gets it's proper name in pi.alert, but I get (name not found) in NetAlertX, with the default scanning engine ON and Pholus.

What am I doing wrong?

**Comment by jokob-sk** [comment]
Hi @stanelie ,

NetAlertX is running in a container, so some additional steps might be needed to get the name discovery working. Please check the following docs:

https://github.com/jokob-sk/NetAlertX/blob/main/docs/REVERSE_DNS.md

If the issue is specifically related to Windows devices, try enabling `NBTSCAN` and `NSLOOKUP` as they might help with discovering names of Windows devices.

**Comment by stanelie** [comment]
I am unable to find the docker-compose.yml file on the system where I installed the NetAlertX docker container. Where is this file located?

**Comment by stanelie** [comment]
I found this helpful bug report with instructions on how to use the docker-compose-yml file for people unfamiliar with it, like me. Maybe this should be included in the documentation.

However, I am running into an issue : 
` unable to start container process: error during container init: error mounting "/home/netalertx/compose/config/resolv.conf" to rootfs at "/etc/resolv.conf": mount /home/netalertx/compose/config/resolv.conf:/etc/resolv.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

I am using the line provided in the documentation : 
`      - ./config/resolv.conf:/etc/resolv.conf`

Thoughts?

**Comment by stanelie** [comment]
I fixed it using a distinct resolv.conf that I put in the config directory, instead of having the docker-compose.yml file point to my /etc/resolv.conf file, as per the documentation. My setup didn't like it.

My current line in docker-compose.yml is
`     - ./config/resolv.conf:/home/netalertx/resolv.conf`

**Comment by stanelie** [comment]
Update : 
I had everything backwards in the docker-compose.yml file.
Here is my current, working docker-compose.yml : 
```
version: "3"
services:
  netalertx:
    container_name: netalertx
    image: "jokobsk/netalertx:latest"
    restart: unless-stopped
    volumes:
      -  /home/netalertx/config:/app/config
      -  /home/netalertx/db:/app/db
      -  /home/netalertx/log:/app/front/log
      -  /home/netalertx/config/resolv.conf:/etc/resolv.conf
    environment:
      - TZ=America/Montreal
      - PORT=80
    ports:
      - "80:80"
    network_mode: host
```

I will come back here with results concerning the name resolution now that I have a correctly configured resolv.conf file.

**Comment by stanelie** [comment]
Well,
It didn't work. On pi.alert, a newly connected device got its hostname properly labeled, while I got (name not found) on NetAlertX.
What else can I try?

**Comment by jokob-sk** [comment]
Hi there,

Can you please confirm that you have enabled the NBTSCAN and NSLOOKUP plugins?

If yes, can you please enable debug and post your log?

**Comment by stanelie** [comment]
Both plugins are enabled.

Which log do you require? Also, how do I send it to you? I'd rather not post the whole thing here, some info in there is sensitive.
Thanks!

**Comment by stanelie** [comment]
Here goes.
[app.log](https://github.com/user-attachments/files/17197436/app.log)

**Comment by jokob-sk** [comment]
Hi @stanelie ,

Thanks for the logs! You can also send them to netalertx@gmail.com in future.

It seems none of the name recognition plugins seem to return any results. 

Can you try to ssh into the container and run the following command?

To ssh into a container run this command on the host (`netalertx` is the container name):

1. SSH into the container
`sudo docker exec -it netalertx /bin/bash`
2. Run this command
`nslookup <IP of Linux host>`


This is how the result should look like:

```bash
jokob@Synology-NAS:$ sudo docker exec -it netalertx /bin/bash
Password: 
Synology-NAS:/# nslookup 192.168.1.58
58.1.168.192.in-addr.arpa       name = ubuntu.localdomain.

Synology-NAS:/# 
```

3. Run command ` nbtscan <IP of win host>`

This is how the result should look like:

```bash
Synology-NAS:/# nbtscan 192.168.1.121
Doing NBT name scan for addresses from 192.168.1.121

IP address       NetBIOS Name     Server    User             MAC address      
------------------------------------------------------------------------------
192.168.1.121    DESKTOP-DIHOG0E  <server>  <unknown>        <mac>
Synology-NAS:/# 
```

If results are empty then something might prevent these scans to be executed from teh container. Can you re-post your docker-compose file?

Could you also please share your `/resolv.conf` file? I would try removing from your docker-compose as a test as well.

**Comment by stanelie** [comment]
Hello.
The docker-compose.yml file is still the same : 
```
version: "3"
services:
  netalertx:
    container_name: netalertx
    image: "jokobsk/netalertx:latest"
    restart: unless-stopped
    volumes:
      -  /home/netalertx/config:/app/config
      -  /home/netalertx/db:/app/db
      -  /home/netalertx/log:/app/front/log
      -  /home/netalertx/config/resolv.conf:/etc/resolv.conf
    environment:
      - TZ=America/Montreal
      - PORT=80
    ports:
      - "80:80"
    network_mode: host
```

I am getting answers from the local 127.0.0.53 address, not from the address I configured in my resolv.conf file.

```
selie@netalertx:~$ nslookup caserne1.caserne
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	caserne1.caserne
Address: 10.8.0.17
```
Here is my resolv.conf : 
```
nameserver 10.8.0.1
nameserver 10.8.0.17
options edns0 trust-ad
search .
```

What else can I do to make the container obey the resolv.conf file?

**Comment by jokob-sk** [comment]
Hey @stanelie ,

According to ChatGPT you can try the following:
```yaml
services:
  netalertx:
    container_name: netalertx
    image: "jokobsk/netalertx:latest"
    restart: unless-stopped
    volumes:
      -  /home/netalertx/config:/app/config
      -  /home/netalertx/db:/app/db
      -  /home/netalertx/log:/app/front/log
      -  /home/netalertx/config/resolv.conf:/etc/resolv.conf
    environment:
      - TZ=America/Montreal
      - PORT=80
    network_mode: host
    dns:
      - 10.8.0.1
      - 10.8.0.17
```

FYI you can remove this part as the container is running on host so port mapping is not required (maybe it could cause issues, but unlikely):

```
    ports:
      - "80:80"
```
