### ISSUE TITLE
[bug] Stuck on AVAHISCAN after Docker install - /app/log/plugins folder is missing

### ISSUE THREAD

**Issue by netExtra** [jokob-sk/NetAlertX#921]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### The issue occurs in the following browsers. Select at least 2.

- [ ] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Safari (unsupported) - PRs welcome
- [ ] N/A - This is an issue with the backend

### Current Behavior

I'm using Opera and Safari, both of which have been working with NetalertX for weeks. Today I tried a new install and it's just stuck on avahiscan with applog error messages;

### Expected Behavior

It works.

### Steps To Reproduce

docker compose up

### app.conf

```python
No changes to default
```

### docker-compose.yml

```python
No changes to default
```

### What branch are you running?

Production

### app.log

11:23:15 [Plugin utils] display_name: AVAHISCAN (Name discovery)
11:23:15 [Plugins] Executing: python3 /app/front/plugins/avahi_scan/avahi_scan.py
11:23:18 [plugin_helper] reading config file
11:23:18 [AVAHISCAN] In script
11:23:18 [Database] Opening DB
11:23:18 [AVAHISCAN] Unknown devices count: 0
Traceback (most recent call last):
  File "/app/front/plugins/avahi_scan/avahi_scan.py", line 212, in <module>
    main()
  File "/app/front/plugins/avahi_scan/avahi_scan.py", line 91, in main
    plugin_objects.write_result_file()
  File "/app/front/plugins/plugin_helper.py", line 240, in write_result_file
    with open(self.result_file, mode="w") as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/app/log/plugins/last_result.AVAHISCAN.log'

11:23:18 [Plugins] ⚠ ERROR - enable LOG_LEVEL=debug and check logs

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi,

It could be a permission issue.

If you have the /app/log folder mapped, try to remove it to test if that
works.

Try checking these docs as well
https://github.com/jokob-sk/NetAlertX/blob/main/docs/FILE_PERMISSIONS.md

Hope this helps,
J

**Comment by netExtra** [comment]
> Hi, It could be a permission issue. If you have the /app/log folder mapped, try to remove it to test if that works. Try checking these docs as well https://github.com/jokob-sk/NetAlertX/blob/main/docs/FILE_PERMISSIONS.md Hope this helps, J
> […](#)

It is a permissions issue but I'm not sure why. I've installed this on my Pi micro SD card many times and it works. Now I'm installing it on a freshly formatted external SSD card and it doesn't.

**Comment by jokob-sk** [comment]
Hi @netExtra ,

Glad to hear it is working without mapping the `/app/log` location, at least we know it is setup related. 

I'm not a permissions wizard so I'd try to grant everyone `a+rwx` and see if that works. Then I would try to slowly remove permissions.  

You can also try to SSH into the container and inspect permissions in there, they might not be mapped as expected. 

Please report back and I can update the guide with more details. 

Hope this helps,
j

**Comment by syerad** [comment]
I'm encountering the same issue for some reason. When I run it directly through Docker, it works, but it doesn’t function with Docker Compose even if I remove all the volumes.

```dockerfile
     container_name: netalertx
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/netalertx-dev:latest"
    image: "jokobsk/netalertx:latest"
    network_mode: "host"
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - PORT=20211
```

**Comment by jokob-sk** [comment]
Hi @syerad ,

I just tried spinning up a fresh container with this compose file and it seems to come up without issues:

```yaml
services:
  netalertx_prod:
    container_name: netalertx_prod
    image: "jokobsk/netalertx:latest"
    network_mode: "host"
#    volumes:
#      - ${APP_DATA_LOCATION}/netalertx_prod/config:/app/config
#      - ${APP_DATA_LOCATION}/netalertx_prod/db:/app/db
    environment:
      - TZ=Europe/Berlin
      - PORT=22224
      - APP_CONF_OVERRIDE={"SCAN_SUBNETS":"['192.168.1.0/24 --interface=eth1']","GRAPHQL_PORT":"20225"}
```

> I only specify APP_CONF_OVERRIDE since my port for the GRAPHQL server 20212 is already used 


1. Even the message is the same, could you please post the whole error message you are getting? 
2. Also, try to delete the container (including temp volumes), image and re-create the container in case the virtual volumes are acting up. 
3. Can you post the command you use to spinning up the container? 

Thanks,
j

**Comment by akorb90** [comment]
Same problem here.

Fresh Debian 12 VM, Deployed using docker compose with portainer.

Stack:
`version: "3"
services:
  netalertx:
    container_name: netalertx
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/netalertx-dev:latest" 
    image: "jokobsk/netalertx:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - ${APP_DATA_LOCATION}/config:/app/config
      - ${APP_DATA_LOCATION}/db/:/app/db/      
      # (optional) useful for debugging if you have issues setting up the container
      - ${APP_DATA_LOCATION}/logs:/app/log
    environment:
      - TZ=${TZ}      
      - PORT=${PORT}`

Env:
`APP_DATA_LOCATION=/opt/netalertx
TZ=Europe/Berlin
PORT=20211`

**Comment by syerad** [comment]
> Hi @syerad ,
> 
> I just tried spinning up a fresh container with this compose file and it seems to come up without issues:
> 
> ```yaml
> services:
>   netalertx_prod:
>     container_name: netalertx_prod
>     image: "jokobsk/netalertx:latest"
>     network_mode: "host"
> #    volumes:
> #      - ${APP_DATA_LOCATION}/netalertx_prod/config:/app/config
> #      - ${APP_DATA_LOCATION}/netalertx_prod/db:/app/db
>     environment:
>       - TZ=Europe/Berlin
>       - PORT=22224
>       - APP_CONF_OVERRIDE={"SCAN_SUBNETS":"['192.168.1.0/24 --interface=eth1']","GRAPHQL_PORT":"20225"}
> ```
> 
> > I only specify APP_CONF_OVERRIDE since my port for the GRAPHQL server 20212 is already used 
> 
> 
> 1. Even the message is the same, could you please post the whole error message you are getting? 
> 2. Also, try to delete the container (including temp volumes), image and re-create the container in case the virtual volumes are acting up. 
> 3. Can you post the command you use to spinning up the container? 
> 
> Thanks,
> j


Thanks @jokob-sk ! I tried the same and it seems to work now. I guess the volumes were acting up. In the next step I'll try re-attach the volumes one by one. Pretty sure it's a permission issue but not yet sure how to resolve it.

Thanks again for your support!

**Comment by jokob-sk** [comment]
@syerad - thanks for the info!

@akorb90 , can you try the following:

1. Backup your setup as per: https://github.com/jokob-sk/NetAlertX/blob/main/docs/BACKUPS.md
1. Delete the container (including temp volumes), and image 
1. Re-create the container
1. Can you post the command you use to spinning up the container?
1. If above doesn't work, can you try commenting out: `#- ${APP_DATA_LOCATION}/logs:/app/log `

**Comment by ingoratsdorf** [comment]
The issue is here:
`FileNotFoundError: [Errno 2] No such file or directory: '/app/log/plugins/last_result.AVAHISCAN.log'`
This happened to me as well with MQTT and other plugins.

Looks like the container is not creating the /app/log/plugins folder.
This is my workaround:
- plugins_vol:/app/log/plugins

```
name: netalertx

services:

  netalertx:
    container_name: netalertx
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/netalertx-dev:latest"
    image: jokobsk/netalertx:latest
    network_mode: "host"
    restart: unless-stopped
    privileged: true
    volumes:
      - /opt/netalertx/config:/app/config
      - /opt/netalertx/db:/app/db
      - log_vol:/app/log # use tmpfs
      **- plugins_vol:/app/log/plugins # use tmpfs**
      - api_vol:/app/api # use tmpfs

    environment:
      - TZ=Pacific/Auckland
      - PORT=20211
volumes:
  api_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  log_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  plugins_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
```

**Comment by jokob-sk** [comment]
Hi @ingoratsdorf ,

I just checked a fresh installation and the folders seem to be created fine:

![image](https://github.com/user-attachments/assets/df29bf37-02f9-4ce4-9ce2-94081abc283d)

Here's my compose:

```yaml

version: "3"
services:
  netalertx_fresh:
    container_name: netalertx_fresh
    image: "jokobsk/netalertx-dev"
    network_mode: "host"
    volumes:
      - ${APP_DATA_LOCATION}/netalertx_fresh/config:/app/config
      - ${APP_DATA_LOCATION}/netalertx_fresh/db:/app/db
    environment:
      - TZ=Australia/Sydney
      - HOST_USER_ID=1036
      - HOST_USER_GID=1000
      - PORT=22222
      - ALWAYS_FRESH_INSTALL=true
      - APP_CONF_OVERRIDE={"SCAN_SUBNETS":"['192.168.1.0/24 --interface=eth1']","GRAPHQL_PORT":"20223","UI_theme":"Light"} 
```
